sudo: required
services:
  - docker

before_install:
  - docker build -t highrez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true highrez/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-tutorial"
  env: "Docker-tutorial-env"
  bucket_name: "elasticbeanstalk-us-east-1-809934709587"
  bucket_path: "docker-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
